[package]
name = "prismx"
version = "0.1.21"
edition = "2021"

[dependencies]
anyhow = "1.0"
crossterm = "0.27"
ratatui = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.6", features = ["v4"] }
lazy_static = "1.4"
log = "0.4"
simplelog = "0.12"
notify = "6.1"
tokio = { version = "1.36", features = ["full"] }
fuzzy-matcher = "0.3"
wasmtime = "14.0"
dirs = "5.0"
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.11"
thiserror = "1.0"
toml = "0.8"

[features]
default = []
config_toml = []