[package]
name = "prismx"
version = "10.1.0"
edition = "2021"
authors = ["Brandon Essex"]
description = "PrismX: Offline-first planning engine with trust, federation, and plugin runtime."

[dependencies]
# Serialization and config
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.7"

# TUI and terminal control
crossterm = "0.27"
ratatui = "0.23"

# Utilities
chrono = "0.4"
dirs = "4.0"
hashbrown = { version = "0.14", default-features = false, features = ["alloc"] }

[features]
default = ["std"]
std = []
