[package]
name = "prismx"
version = "0.1.17"
edition = "2021"

[dependencies]
anyhow = "1.0"
crossterm = "0.27"
ratatui = "0.26"
log = "0.4"
simplelog = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
uuid = { version = "1.4", features = ["v4"] }
dirs = "5.0"
lazy_static = "1.4"
tokio = { version = "1.35", features = ["full"] }
fuzzy-matcher = "0.3"
notify = "6.1"
wasmtime = "14.0"
env_logger = "0.10"
toml = "0.8"