[package]
name = "prismx"
version = "2.0.0-beta"
edition = "2021"
authors = ["BrandonEssex"]
description = "Modular, offline-first planning system centered on a dynamic mindmap interface. "

[dependencies]
anyhow = "1.0"
crossterm = "0.27"
ratatui = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
tokio = { version = "1.28", features = ["full"] }
thiserror = "1.0"
log = "0.4"
simplelog = "0.12"
env_logger = "0.11"
dirs = "5.0"
fuzzy-matcher = "0.3"
wasmtime = { version = "14.0", features = ["wat", "component-model"] }
uuid = { version = "1", features = ["v4", "serde"] }
lazy_static = "1.4"
chrono = { version = "0.4", features = ["serde"] }
toml = "0.8"
notify = "6.1"
rhai = "1.16"