[package]
name = "prismx"
version = "0.1.21"
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
simplelog = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0"
uuid = { version = "1", features = ["v4"] }
crossterm = "0.27"
ratatui = "0.26"
tokio = { version = "1", features = ["full"] }
lazy_static = "1.4"
notify = "6"
fuzzy-matcher = "0.3"
chrono = { version = "0.4", features = ["serde"] }
dirs = "5.0.1"
toml = "0.8"
wasmtime = "14.0.4"