[package]
name = "prismx"
version = "3.0.0"
edition = "2021"
authors = ["Brandon Essex"]
description = "Offline-first engineering TUI with mindmap core and modular plugin system."

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["mindmap", "dashboard", "plugin"]
dashboard = []
mindmap = []
plugin = []
