[layout]
main = 70
sidebar = 30

[keybindings]
resize_main_increase = "Ctrl+Right"
resize_main_decrease = "Ctrl+Left"
toggle_dashboard = "Ctrl+D"
toggle_keymap = "Ctrl+K"
toggle_clipboard = "Ctrl+C"
toggle_spotlight = "Ctrl+O"
toggle_zen = "Ctrl+Z"
