auto_arrange = true
debug_input_mode = true
debug_allow_empty_nodes = true
dock_layout = "vertical"
gemx_beam_color = "Ice"
zen_beam_color = "Ice"
triage_beam_color = "Ice"
settings_beam_color = "Ice"
zen_icon_enabled = true
beamx_panel_theme = "Prism"
beamx_panel_visible = true
mindmap_lanes = true
hierarchy_icons = true
font_style = "Regular"
beam_animation = true
spotlight_auto_width = true
beam_shimmer = true
ghost_link_trails = true
highlight_focus_branch = true
dark_children = true
layout_style = "Compact"
zoom_grid = true
sticky_notes = true
enable_image_drop = true
shortcut_overlay = "Full"
heartbeat_mode = "Pulse"
