auto_arrange = true
debug_input_mode = false
dock_layout = "vertical"
gemx_beam_color = "Prism"
zen_beam_color = "Prism"
triage_beam_color = "Prism"
settings_beam_color = "Prism"
zen_icon_enabled = true
beamx_panel_theme = "Prism"
beamx_panel_visible = true
mindmap_lanes = true
hierarchy_icons = true
font_style = "Bold"
beam_animation = true
spotlight_auto_width = false
beam_shimmer = true
zoom_grid = true
sticky_notes = true
shortcut_overlay = "Contextual"
heartbeat_mode = "Pulse"
