auto_arrange = true
debug_input_mode = true
debug_allow_empty_nodes = false
dock_layout = "vertical"
gemx_beam_color = "Prism"
zen_beam_color = "Prism"
triage_beam_color = "Prism"
settings_beam_color = "Prism"
zen_icon_enabled = true
beamx_panel_theme = "Prism"
beamx_panel_visible = true
mindmap_lanes = true
hierarchy_icons = true
font_style = "Regular"
beam_animation = true
spotlight_auto_width = true
beam_shimmer = true
zoom_grid = false
sticky_notes = true
shortcut_overlay = "Full"
heartbeat_mode = "Pulse"
