auto_arrange = false
debug_input_mode = false
dock_layout = "vertical"
gemx_beam_color = "Prism"
zen_beam_color = "Prism"
triage_beam_color = "Prism"
settings_beam_color = "Prism"
zen_icon_enabled = true
beamx_panel_theme = "Prism"
beamx_panel_visible = true
mindmap_lanes = true
font_style = "Italic"
beam_animation = true
