auto_arrange = false
debug_input_mode = false
dock_layout = "vertical"
gemx_beam_color = "Emerald"
zen_beam_color = "Emerald"
triage_beam_color = "Emerald"
settings_beam_color = "Emerald"
zen_icon_enabled = true
beamx_panel_theme = "Prism"
beamx_panel_visible = true
mindmap_lanes = true
