auto_arrange = false
debug_input_mode = false
dock_layout = "vertical"
gemx_beam_color = "Ice"
zen_beam_color = "Ice"
triage_beam_color = "Ice"
settings_beam_color = "Ice"
zen_icon_enabled = true
zen_icon_glyph = ""
beamx_panel_theme = "Aqua"
beamx_panel_visible = true
