auto_arrange = false
debug_input_mode = false
dock_layout = "vertical"
gemx_beam_color = "Prism"
zen_beam_color = "Aqua"
triage_beam_color = "Aqua"
settings_beam_color = "Aqua"
beamx_panel_theme = "Prism"
beamx_panel_visible = true
