create_child = "tab"
create_sibling = "enter"
delete = "ctrl-d"
drill_down = "ctrl-w"
pop_up = "ctrl-q"
create_free_node = "ctrl-n"
toggle_collapsed = "ctrl-t"
toggle_triage = "ctrl-y"
save = "ctrl-x"
quit = "ctrl-c"
help = "?"
switch_module = "shift-tab"
toggle_edit = "ctrl-e"
toggle_keymap = "ctrl-h"
mode_zen = "ctrl-r"
undo = "ctrl+z"
add_free_node = "ctrl-n"
open_module_switcher = "ctrl-space"
start_drag = "ctrl-r"
start_link = "ctrl-l"
toggle_link_mode = "ctrl-b"
redo = "ctrl-shift-z"
toggle_snap_grid = "ctrl-g"
zen_toggle_theme = "ctrl-a"
