[theme]
mindmap.fg = "cyan"
mindmap.bg = "black"

spotlight.fg = "white"
spotlight.bg = "blue"

keymap.fg = "yellow"
keymap.bg = "black"

clipboard.fg = "magenta"
clipboard.bg = "black"

dashboard.fg = "green"
dashboard.bg = "black"

zen.fg = "white"
zen.bg = "black"

status.fg = "cyan"
status.bg = "black"
