#[derive(Debug, Clone)]
pub enum Action {
    Quit,
    EnterEditNode,
    PushEditChar(char),
    PopEditChar,
    CommitEdit,
    CancelEdit,

    NavigateNext,
    NavigatePrev,
    NavigateParent,
    NavigateChild,
    NavigateLeft,
    NavigateRight,

    CreateSiblingNode,
    CreateChildNode,
    DuplicateNode,
    DeleteNode,

    ToggleZenMode,
    ToggleLogViewer,
    ToggleShortcuts,
    ToggleTriage,
    ToggleDashboard,
    ToggleTimelineView,
    ToggleTagFilterMenu,
    ToggleMindmapLayout,
    OpenContextMenu,
    SearchNode,
    ExpandNode,
    CollapseNode,
    SwitchWorkspace,
    ToggleMarkdownPreview,
}